services:
  kiwi-frontend:
    image: dimagin/kiwi-frontend:latest
    environment:
      - .env
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kiwi-frontend.rule=Host(`kiwiclub.be`)"
      - "traefik.http.routers.kiwi-frontend.entrypoints=websecure"
      - "traefik.http.routers.kiwi-frontend.tls=true"
      - "traefik.http.routers.kiwi-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.kiwi-frontend.service=kiwi-frontend"
      - "traefik.http.services.kiwi-frontend.loadbalancer.server.port=80"
networks:
  traefik-network:
    external: true
